import { describe, expect, it, vi } from 'vitest';

import { fetchTranscriptFromCaptionTracks } from '../src/content/transcript/providers/youtube/captions.js';

describe('YouTube captionTracks: skipAutoGenerated', () => {
  it('skips automaticCaptions + ASR tracks when skipAutoGenerated is true', async () => {
    const fetchImpl = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.startsWith('https://example.com/manual')) {
        return Response.json({ events: [{ segs: [{ utf8: 'Hello manual' }] }] });
      }
      if (url.startsWith('https://example.com/asr')) {
        return Response.json({ events: [{ segs: [{ utf8: 'Hello ASR' }] }] });
      }
      return new Response('', { status: 404 });
    }) as unknown as typeof fetch;

    const html = `ytInitialPlayerResponse = ${JSON.stringify({
      captions: {
        playerCaptionsTracklistRenderer: {
          automaticCaptions: [
            { baseUrl: 'https://example.com/asr', kind: 'asr', languageCode: 'en' },
          ],
          captionTracks: [{ baseUrl: 'https://example.com/manual', kind: '', languageCode: 'en' }],
        },
      },
    })}`;

    const transcript = await fetchTranscriptFromCaptionTracks(fetchImpl, {
      html,
      originalUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
      skipAutoGenerated: true,
      videoId: 'abcdefghijk',
    });

    expect(transcript?.text).toBe('Hello manual');
    expect(transcript?.segments).toBeNull();
    expect(fetchImpl).toHaveBeenCalled();
    expect(fetchImpl.mock.calls.map((call) => String(call[0]))).toEqual(
      expect.not.arrayContaining([expect.stringContaining('example.com/asr')]),
    );
  });

  it('returns null when only auto captions exist and skipAutoGenerated is true', async () => {
    const fetchImpl = vi.fn(async () => new Response('')) as unknown as typeof fetch;

    const html = `ytInitialPlayerResponse = ${JSON.stringify({
      captions: {
        playerCaptionsTracklistRenderer: {
          automaticCaptions: [
            { baseUrl: 'https://example.com/asr', kind: 'asr', languageCode: 'en' },
          ],
          captionTracks: [],
        },
      },
    })}`;

    const transcript = await fetchTranscriptFromCaptionTracks(fetchImpl, {
      html,
      originalUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
      skipAutoGenerated: true,
      videoId: 'abcdefghijk',
    });

    expect(transcript).toBeNull();
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  it('uses auto captions when skipAutoGenerated is false and no manual captions exist', async () => {
    const fetchImpl = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes('example.com/asr')) {
        return Response.json({ events: [{ segs: [{ utf8: 'Hello ASR' }] }] });
      }
      return new Response('', { status: 404 });
    }) as unknown as typeof fetch;

    const html = `ytInitialPlayerResponse = ${JSON.stringify({
      captions: {
        playerCaptionsTracklistRenderer: {
          automaticCaptions: [
            { baseUrl: 'https://example.com/asr', kind: 'asr', languageCode: 'en' },
          ],
        },
      },
    })}`;

    const transcript = await fetchTranscriptFromCaptionTracks(fetchImpl, {
      html,
      originalUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
      skipAutoGenerated: false,
      videoId: 'abcdefghijk',
    });

    expect(transcript?.text).toBe('Hello ASR');
    expect(fetchImpl).toHaveBeenCalled();
  });
});
