function byId<T extends HTMLElement>(id: string): T {
  const el = document.querySelector(`#${id}`);
  if (!el) {throw new Error(`Missing #${id}`);}
  return el as T;
}

export function getOptionsElements() {
  const tabsRoot = byId<HTMLDivElement>('tabs');

  return {
    autoCliFallbackToggleRoot: byId<HTMLDivElement>('autoCliFallbackToggle'),
    autoCliOrderEl: byId<HTMLInputElement>('autoCliOrder'),
    autoToggleRoot: byId<HTMLDivElement>('autoToggle'),
    automationPermissionsBtn: byId<HTMLButtonElement>('automationPermissions'),
    automationToggleRoot: byId<HTMLDivElement>('automationToggle'),
    buildInfoEl: document.getElementById('buildInfo'),
    chatToggleRoot: byId<HTMLDivElement>('chatToggle'),
    daemonStatusEl: byId<HTMLDivElement>('daemonStatus'),
    extendedLoggingToggleRoot: byId<HTMLDivElement>('extendedLoggingToggle'),
    firecrawlModeEl: byId<HTMLSelectElement>('firecrawlMode'),
    fontFamilyEl: byId<HTMLInputElement>('fontFamily'),
    fontSizeEl: byId<HTMLInputElement>('fontSize'),
    formEl: byId<HTMLFormElement>('form'),
    hoverPromptEl: byId<HTMLTextAreaElement>('hoverPrompt'),
    hoverPromptResetBtn: byId<HTMLButtonElement>('hoverPromptReset'),
    hoverSummariesToggleRoot: byId<HTMLDivElement>('hoverSummariesToggle'),
    languageCustomEl: byId<HTMLInputElement>('languageCustom'),
    languagePresetEl: byId<HTMLSelectElement>('languagePreset'),
    logsAutoEl: byId<HTMLInputElement>('logsAuto'),
    logsLevelInputs: Array.from(
      document.querySelectorAll<HTMLInputElement>('input[data-log-level]'),
    ),
    logsMetaEl: byId<HTMLDivElement>('logsMeta'),
    logsOutputEl: byId<HTMLDivElement>('logsOutput'),
    logsParsedEl: byId<HTMLInputElement>('logsParsed'),
    logsRawEl: byId<HTMLPreElement>('logsRaw'),
    logsRefreshBtn: byId<HTMLButtonElement>('logsRefresh'),
    logsSourceEl: byId<HTMLSelectElement>('logsSource'),
    logsTableEl: byId<HTMLTableElement>('logsTable'),
    logsTailEl: byId<HTMLInputElement>('logsTail'),
    markdownModeEl: byId<HTMLSelectElement>('markdownMode'),
    maxCharsEl: byId<HTMLInputElement>('maxChars'),
    maxOutputTokensEl: byId<HTMLInputElement>('maxOutputTokens'),
    modelCustomEl: byId<HTMLInputElement>('modelCustom'),
    modelPresetEl: byId<HTMLSelectElement>('modelPreset'),
    pickersRoot: byId<HTMLDivElement>('pickersRoot'),
    preprocessModeEl: byId<HTMLSelectElement>('preprocessMode'),
    processesAutoEl: byId<HTMLInputElement>('processesAuto'),
    processesLimitEl: byId<HTMLInputElement>('processesLimit'),
    processesLogsCopyBtn: byId<HTMLButtonElement>('processesLogsCopy'),
    processesLogsOutputEl: byId<HTMLPreElement>('processesLogsOutput'),
    processesLogsTitleEl: byId<HTMLDivElement>('processesLogsTitle'),
    processesMetaEl: byId<HTMLDivElement>('processesMeta'),
    processesRefreshBtn: byId<HTMLButtonElement>('processesRefresh'),
    processesShowCompletedEl: byId<HTMLInputElement>('processesShowCompleted'),
    processesStreamEl: byId<HTMLSelectElement>('processesStream'),
    processesTableEl: byId<HTMLTableElement>('processesTable'),
    processesTailEl: byId<HTMLInputElement>('processesTail'),
    promptOverrideEl: byId<HTMLTextAreaElement>('promptOverride'),
    requestModeEl: byId<HTMLSelectElement>('requestMode'),
    retriesEl: byId<HTMLInputElement>('retries'),
    skillsConflictsEl: byId<HTMLDivElement>('skillsImportConflicts'),
    skillsEmptyEl: byId<HTMLDivElement>('skillsEmpty'),
    skillsExportBtn: byId<HTMLButtonElement>('skillsExport'),
    skillsImportBtn: byId<HTMLButtonElement>('skillsImport'),
    skillsListEl: byId<HTMLDivElement>('skillsList'),
    skillsSearchEl: byId<HTMLInputElement>('skillsSearch'),
    slidesOcrToggleRoot: byId<HTMLDivElement>('slidesOcrToggle'),
    slidesParallelToggleRoot: byId<HTMLDivElement>('slidesParallelToggle'),
    statusEl: byId<HTMLSpanElement>('status'),
    summaryTimestampsToggleRoot: byId<HTMLDivElement>('summaryTimestampsToggle'),
    tabButtons: Array.from(tabsRoot.querySelectorAll<HTMLButtonElement>('[data-tab]')),
    tabPanels: Array.from(document.querySelectorAll<HTMLElement>('[data-tab-panel]')),
    tabsRoot,
    timeoutEl: byId<HTMLInputElement>('timeout'),
    tokenCopyBtn: byId<HTMLButtonElement>('tokenCopy'),
    tokenEl: byId<HTMLInputElement>('token'),
    transcriberEl: byId<HTMLSelectElement>('transcriber'),
    userScriptsNoticeEl: byId<HTMLDivElement>('userScriptsNotice'),
    youtubeModeEl: byId<HTMLSelectElement>('youtubeMode'),
  };
}
